name: thermolox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.13.0

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  path_provider: ^2.1.2
  supabase_flutter: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/favicon1.png"
